// swift-tools-version: 6.0
import PackageDescription
let package = Package(name: "VimeSentencePiece", platforms: [.iOS(.v18), .macOS(.v14)],
    products: [.library(name: "VimeSentencePiece", targets: ["CSentencePiece"])],
    targets: [.target(name: "CSentencePiece", sources: [
    "Bridge.cc",
    "vendor/third_party/protobuf-lite/arena.cc",
    "vendor/third_party/protobuf-lite/arenastring.cc",
    "vendor/third_party/protobuf-lite/bytestream.cc",
    "vendor/third_party/protobuf-lite/coded_stream.cc",
    "vendor/third_party/protobuf-lite/common.cc",
    "vendor/third_party/protobuf-lite/extension_set.cc",
    "vendor/third_party/protobuf-lite/generated_enum_util.cc",
    "vendor/third_party/protobuf-lite/generated_message_table_driven_lite.cc",
    "vendor/third_party/protobuf-lite/generated_message_util.cc",
    "vendor/third_party/protobuf-lite/implicit_weak_message.cc",
    "vendor/third_party/protobuf-lite/int128.cc",
    "vendor/third_party/protobuf-lite/io_win32.cc",
    "vendor/third_party/protobuf-lite/message_lite.cc",
    "vendor/third_party/protobuf-lite/parse_context.cc",
    "vendor/third_party/protobuf-lite/repeated_field.cc",
    "vendor/third_party/protobuf-lite/status.cc",
    "vendor/third_party/protobuf-lite/statusor.cc",
    "vendor/third_party/protobuf-lite/stringpiece.cc",
    "vendor/third_party/protobuf-lite/stringprintf.cc",
    "vendor/third_party/protobuf-lite/structurally_valid.cc",
    "vendor/third_party/protobuf-lite/strutil.cc",
    "vendor/third_party/protobuf-lite/time.cc",
    "vendor/third_party/protobuf-lite/wire_format_lite.cc",
    "vendor/third_party/protobuf-lite/zero_copy_stream.cc",
    "vendor/third_party/protobuf-lite/zero_copy_stream_impl.cc",
    "vendor/third_party/protobuf-lite/zero_copy_stream_impl_lite.cc",
    "vendor/src/builtin_pb/sentencepiece.pb.cc",
    "vendor/src/builtin_pb/sentencepiece_model.pb.cc",
    "vendor/src/bpe_model.cc",
    "vendor/src/char_model.cc",
    "vendor/src/error.cc",
    "vendor/src/filesystem.cc",
    "vendor/src/model_factory.cc",
    "vendor/src/model_interface.cc",
    "vendor/src/normalizer.cc",
    "vendor/src/sentencepiece_processor.cc",
    "vendor/src/unigram_model.cc",
    "vendor/src/util.cc",
    "vendor/src/word_model.cc",
    "vendor/third_party/absl/flags/flag.cc"
], publicHeadersPath: "include",
        cxxSettings: [.headerSearchPath("vendor"), .headerSearchPath("vendor/src"),
            .headerSearchPath("vendor/src/builtin_pb"), .headerSearchPath("vendor/third_party"),
            .headerSearchPath("vendor/third_party/protobuf-lite"), .define("HAVE_PTHREAD", to: "1"),
            .define("_USE_INTERNAL_STRING_VIEW"), .define("DISABLE_EMBEDDED_DATA")])],
    cxxLanguageStandard: .cxx17)
